const prompts = [
    { emoji: "☕", text: "A warm drink in your hands" },
    { emoji: "🌅", text: "The sunrise you saw today" },
    { emoji: "💤", text: "Your bed, waiting for you" },
    { emoji: "🚿", text: "Clean water" },
    { emoji: "👂", text: "A song that moved you" },
    { emoji: "🌳", text: "A tree you walked past" },
    { emoji: "🫁", text: "Your breath, right now" },
    { emoji: "👁️", text: "Your ability to read these words" },
    { emoji: "🐕", text: "An animal that made you smile" },
    { emoji: "🪟", text: "The view from your window" },
    { emoji: "🔥", text: "Shelter from the elements" },
    { emoji: "📱", text: "A message from someone who cares" },
    { emoji: "🌙", text: "The moon, always changing" },
    { emoji: "🍎", text: "Food you enjoyed today" },
    { emoji: "🚶", text: "Your legs, carrying you" },
    { emoji: "🧠", text: "Your mind, learning" },
    { emoji: "💚", text: "Your heart, still beating" },
    { emoji: "✋", text: "Your hands, creating" },
    { emoji: "😴", text: "A moment of rest" },
    { emoji: "🌱", text: "Something growing" },
    { emoji: "🔊", text: "Laughter you heard" },
    { emoji: "🕯️", text: "Light in darkness" },
    { emoji: "🫂", text: "A hug you remember" },
    { emoji: "📖", text: "A book that changed you" },
    { emoji: "🎨", text: "Beauty you noticed" },
    { emoji: "⏰", text: "Time you have left" },
    { emoji: "🌍", text: "This strange planet" },
    { emoji: "🪶", text: "Something soft" },
    { emoji: "🌊", text: "The sound of water" },
    { emoji: "🎶", text: "Silence when you need it" },
    { emoji: "🔑", text: "A problem you solved" },
    { emoji: "🌈", text: "Color" },
    { emoji: "🥾", text: "Shoes that fit" },
    { emoji: "💡", text: "An idea that arrived" },
    { emoji: "🪴", text: "Something alive in your space" },
    { emoji: "🌬️", text: "Wind on your skin" },
    { emoji: "⚡", text: "Electricity" },
    { emoji: "🧭", text: "A direction to move" },
    { emoji: "🕊️", text: "A moment of peace" },
    { emoji: "🎁", text: "A gift you gave" },
    { emoji: "🌟", text: "Stars you can't see but know are there" },
    { emoji: "🔮", text: "Mystery" },
    { emoji: "🪁", text: "Play" },
    { emoji: "🧘", text: "Stillness" },
    { emoji: "💭", text: "A memory that makes you smile" },
    { emoji: "🌺", text: "Something blooming" },
    { emoji: "🫶", text: "Love, in any form" },
    { emoji: "🎭", text: "The ability to pretend" },
    { emoji: "🗿", text: "Something that lasted" },
    { emoji: "🌀", text: "Change" }
];
